name: roms_downloader
description: ROMs Downloader
version: 1.0.18+41

environment:
  flutter: ">=3.35.7"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  background_downloader: ^9.3.0
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  path: ^1.9.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  archive: ^4.0.7
  flutter_archive: ^6.0.3
  flutter_foreground_task: ^9.1.0
  package_info_plus: ^9.0.0
  cached_network_image: ^3.4.1
  rapidfuzz: ^0.1.1
  photo_view: ^0.15.0
  disk_space_2: ^1.0.11

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/consoles.json
    - assets/icon.png
